name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - dhruv
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: dhruvsovasaria/myuserapp:latest

      - name: Verify Pushed Image
        run: docker pull dhruvsovasaria/myuserapp:latest
